version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/spring-boot-demo-0.0.1-SNAPSHOT.jar ROOT.jar
artifacts:
  files:
    - ROOT.jar
    - .ebextensions/**/*